### ISSUE TITLE
closed caption disappears from video controls

### ISSUE THREAD

**Issue by danodna** [muxinc/player.style#121]
Hey, I love the possibilities of using player.style! One thing I can't figure out is why the CC icon disappears from my implementation. I have a custom old-school VHS video with a 4/3 aspect ratio and a smaller 320 x 240 size, so it could be this. But I don't even find CC under the gear/settings icon, so I don't know what to do about this. Am I missing something?

I've used player.style once, here: https://monkitale.com/danimations/railroad/

Thank you,
Dan

**Comment by luwes** [comment]
Hi @danodna, thanks for the feedback. Unfortunately the YouTube iframe API lacks API's to list and control caption selection I believe. 
So the themes don't have anything to work with.

Some media types have some restrictions like this because the API's are missing some features. I believe YT is one of the most restrictive ones.
